#!/usr/bin/env bash
#
# robotsix-cai container entrypoint
# ---------------------------------
#
# 1. Template the crontab from env vars. Tasks fall into two groups:
#
#    Pipeline (issue-solving) — a `cai.py cycle` line runs restart-recovery
#    plus a single dispatch via `dispatch_oldest_actionable()`, which picks
#    the oldest open issue/PR whose lifecycle state has a registered handler
#    and runs that handler. A flock in cmd_cycle guarantees at most one cycle
#    runs at a time, so issues are processed serially.
#
#    Orthogonal (independent) tasks — not part of the fix pipeline,
#    so they keep their own schedules:
#      - verify:         label-state reconciliation with GitHub (hourly at :15)
#      - analyze:        parse own transcripts, raise findings as issues (daily at midnight)
#      - audit:          periodic queue/PR consistency checks (every 6 hours)
#      - code-audit:     periodic source code consistency checks (weekly, Sundays 03:00)
#      - propose:        weekly creative improvement proposals (Sundays 04:00)
#      - update-check:   periodic Claude Code release checks (weekly, Mondays 04:00)
#      - health-report:  automated pipeline health report (weekly, Mondays 07:00)
#      - cost-optimize:  weekly cost-reduction proposal or evaluation (Sundays 05:00)
#      - check-workflows: monitor GitHub Actions for failures (every 6 hours)
#      - agent-audit:    weekly audit of .claude/agents/ for consistency and usage (Sundays 06:00)
#      - external-scout: weekly scout for open-source libraries that could replace in-house plumbing (Mondays 06:00)
#
# Environment variables:
#   CAI_WORKSPACES_CONFIG  Path to a JSON file listing additional repos to maintain
#                          (default: /app/workspaces.json). Each entry must have a
#                          "repo" key (e.g. "owner/repo") and an optional
#                          "cycle_schedule" (falls back to CAI_CYCLE_SCHEDULE).
#                          If the file is absent the system behaves as today.
#
# 2. Do one synchronous `cai.py cycle` pass so `docker compose up -d`
#    produces useful logs immediately rather than waiting for the first
#    cron tick. Only the issue-solving cycle runs at startup; the
#    orthogonal tasks wait for their cron ticks so container restarts
#    don't burn tokens re-running them.
#
# 3. Exec supercronic as PID 1. supercronic handles SIGTERM gracefully
#    (lets in-flight tasks finish) and streams child stdout/stderr to
#    its own stdout, which docker logs then captures.

set -euo pipefail

CAI_CYCLE_SCHEDULE="${CAI_CYCLE_SCHEDULE:-0 * * * *}"
CAI_VERIFY_SCHEDULE="${CAI_VERIFY_SCHEDULE:-15 * * * *}"
CAI_ANALYZER_SCHEDULE="${CAI_ANALYZER_SCHEDULE:-0 0 * * *}"
CAI_AUDIT_SCHEDULE="${CAI_AUDIT_SCHEDULE:-0 */6 * * *}"
CAI_CODE_AUDIT_SCHEDULE="${CAI_CODE_AUDIT_SCHEDULE:-0 3 * * 0}"
CAI_PROPOSE_SCHEDULE="${CAI_PROPOSE_SCHEDULE:-0 4 * * 0}"
CAI_UPDATE_CHECK_SCHEDULE="${CAI_UPDATE_CHECK_SCHEDULE:-0 4 * * 1}"
CAI_HEALTH_REPORT_SCHEDULE="${CAI_HEALTH_REPORT_SCHEDULE:-0 7 * * 1}"
CAI_COST_OPTIMIZE_SCHEDULE="${CAI_COST_OPTIMIZE_SCHEDULE:-0 5 * * 0}"
CAI_CHECK_WORKFLOWS_SCHEDULE="${CAI_CHECK_WORKFLOWS_SCHEDULE:-0 */6 * * *}"
CAI_AGENT_AUDIT_SCHEDULE="${CAI_AGENT_AUDIT_SCHEDULE:-0 6 * * 0}"
CAI_EXTERNAL_SCOUT_SCHEDULE="${CAI_EXTERNAL_SCOUT_SCHEDULE:-0 6 * * 1}"
CAI_WORKSPACES_CONFIG="${CAI_WORKSPACES_CONFIG:-/app/workspaces.json}"

CRONTAB_PATH=/tmp/crontab

cat > "$CRONTAB_PATH" <<CRONTAB
# Generated by entrypoint.sh at container startup.
# The single cycle line drives the full issue-solving pipeline;
# other lines are orthogonal tasks with their own cadence.
$CAI_CYCLE_SCHEDULE python /app/cai.py cycle
$CAI_VERIFY_SCHEDULE python /app/cai.py verify
$CAI_ANALYZER_SCHEDULE python /app/cai.py analyze
$CAI_AUDIT_SCHEDULE python /app/cai.py audit
$CAI_CODE_AUDIT_SCHEDULE python /app/cai.py code-audit
$CAI_PROPOSE_SCHEDULE python /app/cai.py propose
$CAI_UPDATE_CHECK_SCHEDULE python /app/cai.py update-check
$CAI_HEALTH_REPORT_SCHEDULE python /app/cai.py health-report
$CAI_COST_OPTIMIZE_SCHEDULE python /app/cai.py cost-optimize
$CAI_CHECK_WORKFLOWS_SCHEDULE python /app/cai.py check-workflows
$CAI_AGENT_AUDIT_SCHEDULE python /app/cai.py agent-audit
$CAI_EXTERNAL_SCOUT_SCHEDULE python /app/cai.py external-scout
CRONTAB

# Append per-workspace cycle lines from the workspaces config file.
if [ -s "$CAI_WORKSPACES_CONFIG" ]; then
  python3 -c "
import json, sys
with open('$CAI_WORKSPACES_CONFIG') as f:
    workspaces = json.load(f)
default_schedule = '$CAI_CYCLE_SCHEDULE'
for entry in workspaces:
    repo = entry.get('repo', '').strip()
    if not repo:
        continue
    schedule = entry.get('cycle_schedule', default_schedule)
    print(schedule + ' CAI_REPO=' + repo + ' python /app/cai.py cycle')
" >> "$CRONTAB_PATH" || echo "[entrypoint] warning: failed to parse $CAI_WORKSPACES_CONFIG"
fi

echo "[entrypoint] crontab:"
sed 's/^/[entrypoint]   /' "$CRONTAB_PATH"
echo

# Wire `gh` in as the git credential helper so the implement subagent can
# `git push` over HTTPS using the same token that's in the
# cai_gh_config volume. ~/.gitconfig isn't persisted across
# container restarts, so we re-run this every startup.
if gh auth status >/dev/null 2>&1; then
  echo "[entrypoint] configuring gh as the git credential helper"
  gh auth setup-git
else
  echo "[entrypoint] gh not yet authenticated; skipping git credential setup"
fi

echo "[entrypoint] running initial cai.py cycle"
python /app/cai.py cycle || echo "[entrypoint] cycle exited non-zero; continuing"

# Run an eager startup cycle for each configured workspace.
if [ -s "$CAI_WORKSPACES_CONFIG" ]; then
  python3 -c "
import json, sys
with open('$CAI_WORKSPACES_CONFIG') as f:
    workspaces = json.load(f)
for entry in workspaces:
    repo = entry.get('repo', '').strip()
    if repo:
        print(repo)
" 2>/dev/null | while IFS= read -r repo; do
    echo "[entrypoint] running initial cai.py cycle for workspace: $repo"
    CAI_REPO="$repo" python /app/cai.py cycle || echo "[entrypoint] cycle for $repo exited non-zero; continuing"
  done
fi

echo "[entrypoint] handing off to supercronic"
exec supercronic "$CRONTAB_PATH"
