#!/usr/bin/env bash
#
# robotsix-cai container entrypoint
# ---------------------------------
#
# 1. Template the crontab from env vars. Tasks fall into two groups:
#
#    Pipeline (issue-solving) — a `cai.py cycle` line runs restart-recovery
#    plus a single dispatch via `dispatch_oldest_actionable()`, which picks
#    the oldest open issue/PR whose lifecycle state has a registered handler
#    and runs that handler. A flock in cmd_cycle guarantees at most one cycle
#    runs at a time, so issues are processed serially.
#
#    Orthogonal (independent) tasks — not part of the fix pipeline,
#    so they keep their own schedules:
#      - verify:         label-state reconciliation with GitHub (hourly at :15)
#      - rescue:         autonomous resume of :human-needed issues without human:solved (every 4 hours at :30)
#
# Environment variables:
#   CAI_WORKSPACES_CONFIG  Path to a JSON file listing additional repos to maintain
#                          (default: /app/workspaces.json). Each entry must have a
#                          "repo" key (e.g. "owner/repo") and an optional
#                          "cycle_schedule" (falls back to CAI_CYCLE_SCHEDULE).
#                          If the file is absent the system behaves as today.
#
# 2. Do one synchronous `cai.py cycle` pass so `docker compose up -d`
#    produces useful logs immediately rather than waiting for the first
#    cron tick. Only the issue-solving cycle runs at startup; the
#    orthogonal tasks wait for their cron ticks so container restarts
#    don't burn tokens re-running them.
#
# 3. Exec supercronic as PID 1. supercronic handles SIGTERM gracefully
#    (lets in-flight tasks finish) and streams child stdout/stderr to
#    its own stdout, which docker logs then captures.

set -euo pipefail

# Runtime UID/GID remap. When docker-compose.yml sets `user: "0:0"` and
# passes HOST_UID/HOST_GID, we enter here as root, remap the in-container
# cai user to match the host user so bind-mounts and named volumes have
# matching ownership, then drop privileges and re-exec this script as
# cai. Running directly as cai (no compose override) makes this branch
# a no-op and the rest of the script runs unchanged.
if [ "$(id -u)" -eq 0 ]; then
  TARGET_UID="${HOST_UID:-1000}"
  TARGET_GID="${HOST_GID:-1000}"
  CURRENT_UID="$(id -u cai)"
  CURRENT_GID="$(id -g cai)"
  if [ "$CURRENT_UID" != "$TARGET_UID" ] || [ "$CURRENT_GID" != "$TARGET_GID" ]; then
    echo "[entrypoint] remapping cai: ${CURRENT_UID}:${CURRENT_GID} -> ${TARGET_UID}:${TARGET_GID}"
    groupmod -g "$TARGET_GID" -o cai
    usermod  -u "$TARGET_UID" -o -g "$TARGET_GID" cai
    # Chown only entries not already at the target UID/GID; full -R chown
    # would rewalk the entire home volume on every container start.
    find /home/cai /var/log/cai /app \
      \( -not -uid "$TARGET_UID" -o -not -gid "$TARGET_GID" \) \
      -exec chown -h "$TARGET_UID:$TARGET_GID" {} + 2>/dev/null || true
  fi
  exec runuser -u cai -- "$0" "$@"
fi

# Preserve explicit empty string as a disable sentinel — use ${VAR-default}
# (unset-only fallback) rather than ${VAR:-default}, so `CAI_*_SCHEDULE=""`
# is NOT silently replaced by the default and can be picked up by
# is_schedule_disabled below.
CAI_CYCLE_SCHEDULE="${CAI_CYCLE_SCHEDULE-0 * * * *}"
CAI_VERIFY_SCHEDULE="${CAI_VERIFY_SCHEDULE-15 * * * *}"
CAI_RESCUE_SCHEDULE="${CAI_RESCUE_SCHEDULE-30 */4 * * *}"
CAI_TRANSCRIPT_SYNC_SCHEDULE="${CAI_TRANSCRIPT_SYNC_SCHEDULE-*/15 * * * *}"
CAI_TRANSCRIPT_SYNC_URL="${CAI_TRANSCRIPT_SYNC_URL:-}"
CAI_WORKSPACES_CONFIG="${CAI_WORKSPACES_CONFIG:-/app/workspaces.json}"

# A schedule is disabled (its crontab line is omitted) when its value
# is the empty string, "disabled", or "off" (case-insensitive). Omitting
# the line avoids supercronic's impossible-cron warning spam.
is_schedule_disabled() {
  local val="${1,,}"
  [[ -z "$val" || "$val" == "disabled" || "$val" == "off" ]]
}

CRONTAB_PATH=/tmp/crontab

cat > "$CRONTAB_PATH" <<CRONTAB
# Generated by entrypoint.sh at container startup.
# The single cycle line drives the full issue-solving pipeline;
# other lines are orthogonal tasks with their own cadence.
CRONTAB

if ! is_schedule_disabled "$CAI_CYCLE_SCHEDULE"; then
  echo "$CAI_CYCLE_SCHEDULE python /app/cai.py cycle" >> "$CRONTAB_PATH"
else
  echo "[entrypoint] CAI_CYCLE_SCHEDULE disabled — skipping cycle cron line"
fi

if ! is_schedule_disabled "$CAI_VERIFY_SCHEDULE"; then
  echo "$CAI_VERIFY_SCHEDULE python /app/cai.py verify" >> "$CRONTAB_PATH"
else
  echo "[entrypoint] CAI_VERIFY_SCHEDULE disabled — skipping verify cron line"
fi

if ! is_schedule_disabled "$CAI_RESCUE_SCHEDULE"; then
  echo "$CAI_RESCUE_SCHEDULE python /app/cai.py rescue" >> "$CRONTAB_PATH"
else
  echo "[entrypoint] CAI_RESCUE_SCHEDULE disabled — skipping rescue cron line"
fi

# Append the transcript-sync cron line only when sync is actually
# configured. The cmd_transcript_sync handler no-ops when disabled, but
# running it every 15 min for no reason would clutter docker logs.
if [ -n "$CAI_TRANSCRIPT_SYNC_URL" ]; then
  if ! is_schedule_disabled "$CAI_TRANSCRIPT_SYNC_SCHEDULE"; then
    echo "$CAI_TRANSCRIPT_SYNC_SCHEDULE python /app/cai.py transcript-sync" >> "$CRONTAB_PATH"
  else
    echo "[entrypoint] CAI_TRANSCRIPT_SYNC_SCHEDULE disabled — skipping transcript-sync cron line"
  fi
fi

# Append per-workspace cycle lines from the workspaces config file.
# When a workspace omits cycle_schedule and the top-level
# CAI_CYCLE_SCHEDULE is disabled, the per-workspace line is also
# skipped — disabling the primary cycle shouldn't silently re-enable
# it for secondary repos.
if [ -s "$CAI_WORKSPACES_CONFIG" ]; then
  python3 -c "
import json, sys
DISABLED = {'', 'disabled', 'off'}
with open('$CAI_WORKSPACES_CONFIG') as f:
    workspaces = json.load(f)
default_schedule = '$CAI_CYCLE_SCHEDULE'
for entry in workspaces:
    repo = entry.get('repo', '').strip()
    if not repo:
        continue
    schedule = entry.get('cycle_schedule', default_schedule)
    if schedule.strip().lower() in DISABLED:
        sys.stderr.write(f'[entrypoint] cycle_schedule disabled for {repo} — skipping workspace cron line\n')
        continue
    print(schedule + ' CAI_REPO=' + repo + ' python /app/cai.py cycle')
" >> "$CRONTAB_PATH" || echo "[entrypoint] warning: failed to parse $CAI_WORKSPACES_CONFIG"
fi

echo "[entrypoint] crontab:"
sed 's/^/[entrypoint]   /' "$CRONTAB_PATH"
echo

# Wire `gh` in as the git credential helper so the implement subagent can
# `git push` over HTTPS using the same token that's in the
# cai_gh_config volume. ~/.gitconfig isn't persisted across
# container restarts, so we re-run this every startup.
if gh auth status >/dev/null 2>&1; then
  echo "[entrypoint] configuring gh as the git credential helper"
  gh auth setup-git
else
  echo "[entrypoint] gh not yet authenticated; skipping git credential setup"
fi

echo "[entrypoint] running initial cai.py cycle"
python /app/cai.py cycle || echo "[entrypoint] cycle exited non-zero; continuing"

# Run an eager startup cycle for each configured workspace.
if [ -s "$CAI_WORKSPACES_CONFIG" ]; then
  python3 -c "
import json, sys
with open('$CAI_WORKSPACES_CONFIG') as f:
    workspaces = json.load(f)
for entry in workspaces:
    repo = entry.get('repo', '').strip()
    if repo:
        print(repo)
" 2>/dev/null | while IFS= read -r repo; do
    echo "[entrypoint] running initial cai.py cycle for workspace: $repo"
    CAI_REPO="$repo" python /app/cai.py cycle || echo "[entrypoint] cycle for $repo exited non-zero; continuing"
  done
fi

echo "[entrypoint] handing off to supercronic"
exec supercronic "$CRONTAB_PATH"
