#!/usr/bin/env bash
#
# robotsix-cai container entrypoint
# ---------------------------------
#
# 1. Template the crontab from env vars. Tasks fall into two groups:
#
#    Pipeline (issue-solving) — a `cai.py cycle` line drives the
#    fix → revise → review-pr → merge → confirm flow on
#    :plan-approved issues, while a separate `cai.py plan-all` line
#    drives :raised and :refined issues through refine → plan → :planned
#    so humans can review and approve plans out-of-band. A flock in
#    cmd_cycle guarantees at most one cycle runs at a time, so issues
#    are processed serially (one full cycle per issue from fix through
#    merge). This replaces the older per-stage cron lines (fix, refine,
#    plan, spike, revise, review-pr, merge, verify, confirm) which
#    could interleave stages across different issues.
#
#    Orthogonal (independent) tasks — not part of the fix pipeline,
#    so they keep their own schedules:
#      - analyze:        parse own transcripts, raise findings as issues
#      - audit:          periodic queue/PR consistency checks
#      - audit-triage:   resolve audit:raised findings
#      - code-audit:     periodic source code consistency checks
#      - propose:        weekly creative improvement proposals
#      - update-check:   periodic Claude Code release checks
#      - health-report:  automated pipeline health report
#      - cost-optimize:  weekly cost-reduction proposal or evaluation
#      - check-workflows: monitor GitHub Actions for failures
#
# 2. Do one synchronous `cai.py cycle` pass so `docker compose up -d`
#    produces useful logs immediately rather than waiting for the first
#    cron tick. Only the issue-solving cycle runs at startup; the
#    orthogonal tasks wait for their cron ticks so container restarts
#    don't burn tokens re-running them.
#
# 3. Exec supercronic as PID 1. supercronic handles SIGTERM gracefully
#    (lets in-flight tasks finish) and streams child stdout/stderr to
#    its own stdout, which docker logs then captures.

set -euo pipefail

CAI_CYCLE_SCHEDULE="${CAI_CYCLE_SCHEDULE:-0 * * * *}"
CAI_PLAN_ALL_SCHEDULE="${CAI_PLAN_ALL_SCHEDULE:-30 * * * *}"
CAI_ANALYZER_SCHEDULE="${CAI_ANALYZER_SCHEDULE:-0 0 * * *}"
CAI_AUDIT_SCHEDULE="${CAI_AUDIT_SCHEDULE:-0 */6 * * *}"
CAI_AUDIT_TRIAGE_SCHEDULE="${CAI_AUDIT_TRIAGE_SCHEDULE:-10 */6 * * *}"
CAI_CODE_AUDIT_SCHEDULE="${CAI_CODE_AUDIT_SCHEDULE:-0 3 * * 0}"
CAI_PROPOSE_SCHEDULE="${CAI_PROPOSE_SCHEDULE:-0 4 * * 0}"
CAI_UPDATE_CHECK_SCHEDULE="${CAI_UPDATE_CHECK_SCHEDULE:-0 4 * * 1}"
CAI_HEALTH_REPORT_SCHEDULE="${CAI_HEALTH_REPORT_SCHEDULE:-0 7 * * 1}"
CAI_COST_OPTIMIZE_SCHEDULE="${CAI_COST_OPTIMIZE_SCHEDULE:-0 5 * * 0}"
CAI_CHECK_WORKFLOWS_SCHEDULE="${CAI_CHECK_WORKFLOWS_SCHEDULE:-0 */6 * * *}"

CRONTAB_PATH=/tmp/crontab

cat > "$CRONTAB_PATH" <<CRONTAB
# Generated by entrypoint.sh at container startup.
# The single cycle line drives the full issue-solving pipeline;
# other lines are orthogonal tasks with their own cadence.
$CAI_CYCLE_SCHEDULE python /app/cai.py cycle
$CAI_PLAN_ALL_SCHEDULE python /app/cai.py plan-all
$CAI_ANALYZER_SCHEDULE python /app/cai.py analyze
$CAI_AUDIT_SCHEDULE python /app/cai.py audit
$CAI_AUDIT_TRIAGE_SCHEDULE python /app/cai.py audit-triage
$CAI_CODE_AUDIT_SCHEDULE python /app/cai.py code-audit
$CAI_PROPOSE_SCHEDULE python /app/cai.py propose
$CAI_UPDATE_CHECK_SCHEDULE python /app/cai.py update-check
$CAI_HEALTH_REPORT_SCHEDULE python /app/cai.py health-report
$CAI_COST_OPTIMIZE_SCHEDULE python /app/cai.py cost-optimize
$CAI_CHECK_WORKFLOWS_SCHEDULE python /app/cai.py check-workflows
CRONTAB

echo "[entrypoint] crontab:"
sed 's/^/[entrypoint]   /' "$CRONTAB_PATH"
echo

# Wire `gh` in as the git credential helper so the fix subagent can
# `git push` over HTTPS using the same token that's in the
# cai_gh_config volume. ~/.gitconfig isn't persisted across
# container restarts, so we re-run this every startup.
if gh auth status >/dev/null 2>&1; then
  echo "[entrypoint] configuring gh as the git credential helper"
  gh auth setup-git
else
  echo "[entrypoint] gh not yet authenticated; skipping git credential setup"
fi

echo "[entrypoint] running initial cai.py cycle"
python /app/cai.py cycle || echo "[entrypoint] cycle exited non-zero; continuing"

echo "[entrypoint] handing off to supercronic"
exec supercronic "$CRONTAB_PATH"
