#!/usr/bin/env bash
#
# robotsix-cai installer
# ----------------------
#
# Generates a minimal docker-compose.yml configured for your chosen
# authentication mode. After this script finishes, you can `cd` into the
# install directory and `docker compose up` to run the container.
#
# Usage (download then run, recommended):
#
#   wget https://raw.githubusercontent.com/damien-robotsix/robotsix-cai/main/install.sh
#   less install.sh    # review before running
#   bash install.sh
#
# Or piped (skips review):
#
#   wget -qO- https://raw.githubusercontent.com/damien-robotsix/robotsix-cai/main/install.sh | bash
#
# Environment variables (optional):
#
#   INSTALL_DIR  Directory to install into. Default: ./robotsix-cai
#   IMAGE_TAG    Docker image tag to pin.   Default: latest

set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-$(pwd)/robotsix-cai}"
IMAGE_TAG="${IMAGE_TAG:-latest}"

# Resolve a TTY for interactive prompts. This makes the piped form
# (wget -qO- ... | bash) work — stdin is consumed by the pipe, so we
# read user input directly from the controlling terminal when one
# exists. If there's no controlling terminal (e.g. CI, headless),
# we fall back to whatever stdin is.
if (exec < /dev/tty) 2>/dev/null; then
  TTY=/dev/tty
else
  TTY=/dev/stdin
fi

# Prompts always print to stderr so they're visible even when stdout is
# redirected and even when /dev/tty isn't openable.
prompt() {
  local var="$1" message="$2" default="${3:-}"
  local input
  if [[ -n "$default" ]]; then
    printf "%s [%s]: " "$message" "$default" >&2
  else
    printf "%s: " "$message" >&2
  fi
  IFS= read -r input < "$TTY"
  printf -v "$var" '%s' "${input:-$default}"
}

echo "robotsix-cai installer"
echo "======================"
echo
echo "Install directory: $INSTALL_DIR"
echo "Image:             robotsix/cai:$IMAGE_TAG"
echo

mkdir -p "$INSTALL_DIR/logs"
cd "$INSTALL_DIR"

if [[ -e docker-compose.yml ]]; then
  echo "[!] $INSTALL_DIR/docker-compose.yml exists; it will be overwritten."
  echo
fi

echo "How should the container authenticate to Claude?"
echo
echo "  1) Open the claude REPL inside the container — it auto-prompts"
echo "     for OAuth login on first start (recommended; credentials land"
echo "     in the cai_home volume and persist across restarts; no static"
echo "     secret stored in the container env. The installer opens the"
echo "     REPL for you automatically.)"
echo
echo "  2) Use an Anthropic API key (you'll be prompted to paste it)"
echo

prompt AUTH_CHOICE "Choice" "1"

echo
echo "Enable Watchtower for automatic updates?"
echo
echo "Watchtower is a small sidecar container that polls Docker Hub"
echo "every 30 minutes and automatically pulls + restarts cai when a"
echo "new image is published. Recommended for hands-off operation."
echo
echo "WARNING: if cai is mid-fix when watchtower restarts it, the"
echo "in-flight fix will be killed and the issue may be left stuck"
echo "in auto-improve:in-progress. Manual relabel may be needed"
echo "until the audit feature (tracked separately) lands."
echo
prompt ENABLE_WATCHTOWER "Enable Watchtower? [y/N]" "n"

case "$ENABLE_WATCHTOWER" in
  y|Y|yes|Yes|YES)
    WATCHTOWER_SERVICE=$(cat <<'WATCHTOWER'

  watchtower:
    image: nickfedor/watchtower:1.16.1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --label-enable
      - --interval=1800
      - --cleanup
WATCHTOWER
)
    CAI_LABEL_BLOCK=$(cat <<'LABEL'
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
LABEL
)
    ;;
  *)
    WATCHTOWER_SERVICE=""
    CAI_LABEL_BLOCK=""
    ;;
esac

case "$AUTH_CHOICE" in
  1)
    cat > docker-compose.yml <<YAML
# Generated by robotsix-cai install.sh
# Auth mode: in-container claude REPL OAuth (credentials in cai_home volume)
services:
  cai:
    image: robotsix/cai:${IMAGE_TAG}
    restart: unless-stopped
    environment:
      # Crontab expressions for the four scheduled tasks (any valid
      # 5-field cron line — see https://crontab.guru/). Defaults
      # stagger them so they never overlap.
      CAI_ANALYZER_SCHEDULE: "0 0 * * *"   # daily 00:00 UTC (LLM call)
      CAI_FIX_SCHEDULE: "15 * * * *"        # hourly :15 (cheap if no work)
      CAI_REFINE_SCHEDULE: "10 * * * *"     # hourly :10 (structure human-filed issues)
      CAI_REVISE_SCHEDULE: "30 * * * *"     # hourly :30 (iterate on PR comments)
      CAI_VERIFY_SCHEDULE: "45 * * * *"     # hourly :45 (no LLM)
      CAI_AUDIT_SCHEDULE: "0 */6 * * *"     # every 6h (Sonnet, report-only + branch cleanup)
      CAI_AUDIT_TRIAGE_SCHEDULE: "10 */6 * * *" # every 6h at :10 (triage raised findings)
      CAI_CODE_AUDIT_SCHEDULE: "0 3 * * 0"  # weekly Sunday 03:00 UTC (Sonnet, code consistency)
      CAI_PROPOSE_SCHEDULE: "0 4 * * 0"    # weekly Sunday 04:00 UTC (creative improvement proposals)
      CAI_UPDATE_CHECK_SCHEDULE: "0 4 * * 1" # weekly Monday 04:00 UTC (Claude Code release check)
      CAI_CONFIRM_SCHEDULE: "0 2 * * *"     # daily 02:00 UTC (verify merged fixes)
      CAI_REVIEW_PR_SCHEDULE: "20 * * * *"  # hourly :20 (pre-merge consistency review)
      CAI_MERGE_SCHEDULE: "35 * * * *"      # hourly :35 (auto-merge confident PRs)
      CAI_MERGE_CONFIDENCE_THRESHOLD: "high" # high | medium | disabled
      CAI_TRANSCRIPT_WINDOW_DAYS: "7"       # only parse sessions from last N days
      CAI_TRANSCRIPT_MAX_FILES: "50"        # read at most N recent transcript files (0 = no limit)
    volumes:
      # Persistent state for the cai user (Claude OAuth credentials,
      # session transcripts, gh config, claude-code's runtime
      # \`.claude.json\` config file, etc.). Mounted at /home/cai
      # rather than /home/cai/.claude so that BOTH the .claude/
      # directory AND its sibling .claude.json file are captured —
      # the latter is where claude-code stores runtime config and
      # would otherwise be lost on every container restart.
      #
      # Authenticate once with:
      #     docker compose run --rm -it cai claude
      # (the REPL auto-prompts for OAuth login on first start; exit
      # with /exit or Ctrl-D to flush credentials to disk)
      - cai_home:/home/cai
      # Persistent per-agent memory (\`.claude/agent-memory/<name>/\`)
      # so the durable notes each subagent accumulates across runs
      # survive container restarts.
      - cai_agent_memory:/app/.claude/agent-memory
      - ./logs:/var/log/cai
${CAI_LABEL_BLOCK}${WATCHTOWER_SERVICE}

volumes:
  cai_home:
    name: cai_home
  cai_agent_memory:
    name: cai_agent_memory
YAML
    echo
    echo "[OK] Wrote $INSTALL_DIR/docker-compose.yml (in-container OAuth mode)"
    ;;
  2)
    prompt API_KEY "Anthropic API key (sk-ant-...)"
    if [[ -z "$API_KEY" ]]; then
      echo "ERROR: API key cannot be empty."
      exit 1
    fi
    cat > docker-compose.yml <<YAML
# Generated by robotsix-cai install.sh
# Auth mode: API key from .env
services:
  cai:
    image: robotsix/cai:${IMAGE_TAG}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Crontab expressions for the four scheduled tasks (any valid
      # 5-field cron line — see https://crontab.guru/). Defaults
      # stagger them so they never overlap.
      CAI_ANALYZER_SCHEDULE: "0 0 * * *"   # daily 00:00 UTC (LLM call)
      CAI_FIX_SCHEDULE: "15 * * * *"        # hourly :15 (cheap if no work)
      CAI_REFINE_SCHEDULE: "10 * * * *"     # hourly :10 (structure human-filed issues)
      CAI_REVISE_SCHEDULE: "30 * * * *"     # hourly :30 (iterate on PR comments)
      CAI_VERIFY_SCHEDULE: "45 * * * *"     # hourly :45 (no LLM)
      CAI_AUDIT_SCHEDULE: "0 */6 * * *"     # every 6h (Sonnet, report-only + branch cleanup)
      CAI_AUDIT_TRIAGE_SCHEDULE: "10 */6 * * *" # every 6h at :10 (triage raised findings)
      CAI_CODE_AUDIT_SCHEDULE: "0 3 * * 0"  # weekly Sunday 03:00 UTC (Sonnet, code consistency)
      CAI_PROPOSE_SCHEDULE: "0 4 * * 0"    # weekly Sunday 04:00 UTC (creative improvement proposals)
      CAI_UPDATE_CHECK_SCHEDULE: "0 4 * * 1" # weekly Monday 04:00 UTC (Claude Code release check)
      CAI_CONFIRM_SCHEDULE: "0 2 * * *"     # daily 02:00 UTC (verify merged fixes)
      CAI_REVIEW_PR_SCHEDULE: "20 * * * *"  # hourly :20 (pre-merge consistency review)
      CAI_MERGE_SCHEDULE: "35 * * * *"      # hourly :35 (auto-merge confident PRs)
      CAI_MERGE_CONFIDENCE_THRESHOLD: "high" # high | medium | disabled
      CAI_TRANSCRIPT_WINDOW_DAYS: "7"       # only parse sessions from last N days
      CAI_TRANSCRIPT_MAX_FILES: "50"        # read at most N recent transcript files (0 = no limit)
    volumes:
      # Persistent state for the cai user (Claude transcripts, gh
      # config, claude-code's runtime \`.claude.json\`, etc.).
      # API-key auth means the volume can stay empty for credentials,
      # but transcripts and other claude-code config still
      # accumulate here.
      - cai_home:/home/cai
      # Persistent per-agent memory (\`.claude/agent-memory/<name>/\`)
      # so the durable notes each subagent accumulates across runs
      # survive container restarts.
      - cai_agent_memory:/app/.claude/agent-memory
      - ./logs:/var/log/cai
${CAI_LABEL_BLOCK}${WATCHTOWER_SERVICE}

volumes:
  cai_home:
    name: cai_home
  cai_agent_memory:
    name: cai_agent_memory
YAML
    cat > .env <<ENV
ANTHROPIC_API_KEY=${API_KEY}
ENV
    chmod 600 .env
    echo
    echo "[OK] Wrote $INSTALL_DIR/docker-compose.yml (API-key mode)"
    echo "[OK] Wrote $INSTALL_DIR/.env with your API key (chmod 600)"
    ;;
  *)
    echo "ERROR: invalid choice '$AUTH_CHOICE'."
    exit 1
    ;;
esac

echo
echo "Pulling the cai image..."
echo
if ! docker compose pull; then
  echo
  echo "[!] 'docker compose pull' failed. If you're developing locally, you"
  echo "    can build from source instead: 'docker compose build'"
  exit 1
fi

# Wipe any existing cai volumes so the install starts from a clean
# state. This is important on re-install / upgrade because earlier
# versions used different volume layouts (cai_claude, cai_gh_config,
# cai_transcripts) that no longer match the current
# (cai_home + cai_agent_memory) layout. Stale volumes can also have
# wrong-ownership files left over from when the container ran as
# root. Easier to wipe and start fresh than to migrate.
echo
echo "Wiping any existing cai volumes for a clean install..."
for vol in cai_home cai_agent_memory cai_claude cai_gh_config cai_transcripts; do
  if docker volume inspect "$vol" >/dev/null 2>&1; then
    if docker volume rm "$vol" >/dev/null 2>&1; then
      echo "  removed: $vol"
    else
      echo "  [!] failed to remove $vol (still in use? stop other containers using it first)"
    fi
  fi
done
echo

echo
echo "Authenticating gh inside the container (interactive)."
echo "Credentials persist in the cai_home volume so subsequent"
echo "'docker compose up' runs don't need to re-authenticate."
echo
echo "When prompted, pick:"
echo "  * 'GitHub.com'"
echo "  * 'HTTPS'"
echo "  * Authenticate via web browser (easiest on a headless server —"
echo "    gh prints a one-time code and a URL to open)"
echo

# 'docker compose run' needs a real TTY for the interactive prompts.
# The piped form of the installer (wget -qO- | bash) consumes stdin, so
# we redirect stdin from /dev/tty when we have one. Without a TTY, we
# fall back to printing the command and letting the user run it.
if [[ "$TTY" == "/dev/tty" ]]; then
  if ! docker compose run --rm cai gh auth login --git-protocol https < /dev/tty; then
    echo
    echo "[!] gh auth login did not complete. Rerun it yourself:"
    echo "      cd $INSTALL_DIR && docker compose run --rm cai gh auth login --git-protocol https"
    exit 1
  fi
  echo
  echo "[OK] gh is authenticated. Credentials persisted in cai_home."

  # Same pattern for claude — only relevant in OAuth mode (AUTH_CHOICE=1).
  # API-key mode (AUTH_CHOICE=2) uses ANTHROPIC_API_KEY from .env, no
  # interactive login needed.
  #
  # We open the claude REPL with `docker compose run --rm -it cai claude`.
  # On first start (no credentials in the cai_home volume), the REPL
  # automatically prompts for OAuth login — the user completes the
  # browser flow, claude saves credentials to the volume, and the
  # user exits the REPL.
  #
  # Why the REPL form instead of `claude auth login` (the obvious
  # CLI subcommand): the latter does NOT work reliably under
  # `docker compose run -it < /dev/tty`. The CLI subcommand's input
  # mechanism doesn't play well with the pseudo-TTY layer — the user
  # pastes the authorization code and it silently never reaches claude.
  # The REPL uses the full terminal handling code path that does
  # propagate the paste correctly.
  if [[ "$AUTH_CHOICE" == "1" ]]; then
    echo
    echo "Authenticating claude inside the container (interactive)."
    echo "Credentials persist in the cai_home volume so subsequent"
    echo "'docker compose up' runs don't need to re-authenticate."
    echo
    echo "We're about to open the claude REPL. On first start, it will"
    echo "automatically prompt you to log in:"
    echo "  1. The REPL opens a browser to the OAuth page"
    echo "  2. Complete the sign-in and copy the authorization code"
    echo "  3. Paste the code back into the REPL and press Enter"
    echo "  4. Once login is confirmed, exit the REPL gracefully:"
    echo "       type /exit, or press Ctrl-D"
    echo "     (Ctrl-C also works but may interrupt before claude flushes"
    echo "      the credentials and config to disk — use it only if"
    echo "      nothing else does)"
    echo
    echo "Press Enter when you're ready..."
    read -r _ < /dev/tty || true
    if ! docker compose run --rm -it cai claude < /dev/tty; then
      # The REPL may exit non-zero (Ctrl-C, Ctrl-D, etc.); don't
      # treat that as an error — it auto-prompts on next start.
      :
    fi
    echo
  fi

  echo
  echo "Next steps:"
  echo "  cd $INSTALL_DIR"
  echo "  docker compose up -d                    # start the scheduler"
  echo "  docker compose logs -f cai              # watch the first cycle"
  echo
  echo "Override the schedule by editing docker-compose.yml's"
  echo "CAI_ANALYZER_SCHEDULE env var (any valid cron expression)."
  echo
  echo "Trigger an ad-hoc analyzer run without waiting for the tick:"
  echo "  docker compose exec cai python /app/cai.py analyze"
else
  echo "[!] No controlling TTY — skipping the interactive login."
  echo "    Finish authentication yourself before the first run:"
  echo "      cd $INSTALL_DIR"
  echo "      docker compose run --rm cai gh auth login --git-protocol https"
  if [[ "$AUTH_CHOICE" == "1" ]]; then
    echo "      docker compose run --rm -it cai claude    # then complete the OAuth prompt"
  fi
  echo "      docker compose up -d"
fi
