#!/usr/bin/env bash
# robotsix-cai installer (minimal).
#
# Generates a docker-compose.yml in INSTALL_DIR, pulls the image,
# walks you through Claude + GitHub auth, and optionally adds a
# `cai` shell alias. Re-run safely.
#
# Usage:
#   wget https://raw.githubusercontent.com/damien-robotsix/robotsix-cai/main/install.sh
#   bash install.sh
#
# Env vars:
#   INSTALL_DIR  Install location (default: ./robotsix-cai)
#   IMAGE_TAG    Image tag to pin  (default: latest)

set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-$(pwd)/robotsix-cai}"
IMAGE_TAG="${IMAGE_TAG:-latest}"

# Resolve a TTY for interactive prompts so the piped form
# (wget -qO- ... | bash) still reads input from the controlling
# terminal instead of the consumed stdin.
if (exec < /dev/tty) 2>/dev/null; then
  TTY=/dev/tty
else
  TTY=/dev/stdin
fi

prompt() {
  local var="$1" message="$2" default="${3:-}"
  local input
  if [[ -n "$default" ]]; then
    printf "%s [%s]: " "$message" "$default" >&2
  else
    printf "%s: " "$message" >&2
  fi
  IFS= read -r input < "$TTY"
  printf -v "$var" '%s' "${input:-$default}"
}

echo "robotsix-cai installer"
echo "======================"
echo "Install dir: $INSTALL_DIR"
echo "Image:       robotsix/cai:$IMAGE_TAG"
echo

mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

cat > docker-compose.yml <<EOF
services:
  cai:
    image: robotsix/cai:${IMAGE_TAG}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - cai_home:/home/cai

volumes:
  cai_home:
    name: cai_home
EOF

DC="docker compose -f ${INSTALL_DIR}/docker-compose.yml"

echo "Claude authentication:"
echo "  1) OAuth login (recommended; persisted in cai_home volume)"
echo "  2) Anthropic API key"
prompt AUTH_CHOICE "Choice" "1"

if [[ "$AUTH_CHOICE" == "2" ]]; then
  prompt API_KEY "Anthropic API key"
  printf 'ANTHROPIC_API_KEY=%s\n' "$API_KEY" > .env
else
  : > .env
fi

$DC pull
$DC up -d

if [[ "$AUTH_CHOICE" != "2" ]]; then
  echo
  echo "Launching claude REPL for OAuth login. Type /exit when done."
  $DC exec --user cai cai claude
fi

echo
echo "Authenticating with GitHub..."
$DC exec --user cai cai gh auth login

echo
echo "Add a 'cai' alias to your shell rc?"
echo "    cai     opens an interactive claude session in the container"
prompt ADD_ALIAS "Add alias? [y/N]" "n"

case "$ADD_ALIAS" in
  y|Y|yes|YES)
    USER_SHELL="$(basename "${SHELL:-/bin/bash}")"
    case "$USER_SHELL" in
      zsh)  RC_DEFAULT="${HOME}/.zshrc" ;;
      *)    RC_DEFAULT="${HOME}/.bashrc" ;;
    esac
    prompt RC_FILE "Shell rc file" "$RC_DEFAULT"

    ALIAS_LINE="alias cai='${DC} exec --user cai cai python /app/cai.py'"
    if grep -qF '# robotsix-cai alias' "$RC_FILE" 2>/dev/null; then
      sed -i '/^# robotsix-cai alias/,/^alias cai=/d' "$RC_FILE"
    fi
    {
      echo
      echo "# robotsix-cai alias (generated by install.sh)"
      echo "$ALIAS_LINE"
    } >> "$RC_FILE"
    echo "Wrote alias to $RC_FILE. Run 'source $RC_FILE' or open a new terminal."
    ;;
esac

echo
echo "Done. Try: cai"
