"""Per-thread graph for ``cai-address``.

For each unresolved review thread (that wasn't authored by ``cai[bot]``):

1. Run the address agent against the live PR checkout.
2. If it chose ``fix`` and the working tree changed, commit on the PR branch.
3. Post the agent's reply on the thread.
4. If a fix landed, resolve the thread.

After the loop, if any commit was made, push the branch once.

Modeled as a pydantic-graph: ListThreadsNode → ProcessThreadNode (self-loops
while the queue has work) → PushNode → End. The shape of the graph is
authoritative for the documentation diagrams generated by
``scripts/gen_workflow_graphs.py``.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Literal

from git import Repo
from pydantic import BaseModel, Field
from pydantic_ai.exceptions import ModelRetry
from pydantic_ai.usage import UsageLimits
from pydantic_graph import BaseNode, End, Graph, GraphRunContext

from cai.agents.loader import AGENT_DIR, build_deep_agent, parse_agent_md
from cai.git import commit, push_branch, stage_all
from cai.github.bot import CaiBot
from cai.github.pr import (
    ReviewThread,
    list_resolved_threads,
    list_unresolved_threads,
    reply_to_review_comment,
    resolve_review_thread,
)
from cai.github.repo import PRWorkspace
from cai.log import langfuse_workflow
from cai.workflows._deps import repo_deps

AGENT_DEFINITION = AGENT_DIR / "address.md"


class AddressDecision(BaseModel):
    action: Literal["fix", "reply_only"] = Field(
        description="Whether the agent edited code (fix) or only wants to reply (reply_only)."
    )
    reply: str = Field(description="Message to post as a reply on the thread.")
    commit_message: str | None = Field(
        default=None,
        description="Imperative-mood commit subject. Required when action=fix.",
    )


@dataclass
class ThreadResult:
    thread_id: str
    path: str
    action: Literal["fix", "reply_only", "skipped"]
    committed: bool
    resolved: bool


@lru_cache(maxsize=1)
def _address_agent():
    config, instructions = parse_agent_md(AGENT_DEFINITION)
    agent = build_deep_agent(config, instructions, output_type=AddressDecision)

    @agent.output_validator
    async def _fix_must_edit(ctx, decision: AddressDecision) -> AddressDecision:
        # Without this guard the agent can claim ``action="fix"`` and post a
        # confident reply on the thread without ever calling Write/Edit. The
        # caller would then post the misleading reply but commit nothing.
        if decision.action != "fix":
            return decision
        repo_root = Path(ctx.deps.backend.root_dir)
        if not Repo(str(repo_root)).is_dirty(
            index=True, working_tree=True, untracked_files=True
        ):
            raise ModelRetry(
                "You returned action='fix' but the working tree has no changes "
                "— no edits were made on disk. Either invoke write_file or "
                "hashline_edit to actually make the change you described, or "
                "return action='reply_only' if a code change is not warranted."
            )
        return decision

    return agent


def _format_thread_prompt(
    thread: ReviewThread,
    workspace: PRWorkspace,
    prior_corrections: list[ReviewThread],
) -> str:
    """Render the thread as a prompt the agent can act on.

    The PR title/body frame the surrounding goal. The "Prior corrections"
    section lists already-resolved threads on the same PR so the agent
    doesn't undo earlier fixes — without this, an agent reading the
    (potentially stale) PR body could re-add code that a prior thread
    explicitly removed.
    """
    line = thread.line if thread.line is not None else "(line unknown)"
    history = "\n\n".join(
        f"**{c.author}** ({c.created_at}):\n{c.body}" for c in thread.comments
    )

    sections = [
        "Address this PR review thread.\n",
        (
            "## Pull request (background, may be stale)\n\n"
            f"**{workspace.repo}#{workspace.number}** — {workspace.title}\n\n"
            "The body below is the original plan. Prior review threads "
            "and commits on this branch may have corrected it; the "
            "current state of the code and the *Prior corrections* "
            "section are authoritative over the plan.\n\n"
            f"{workspace.body}"
        ),
    ]
    if prior_corrections:
        rendered = "\n\n".join(_render_resolved_thread(t) for t in prior_corrections)
        sections.append(
            "## Prior corrections (resolved threads on this PR)\n\n"
            "Do not undo these — the fixes already landed.\n\n" + rendered
        )
    sections.append(f"## File\n\n`{thread.path}` at line {line}")
    sections.append(f"## Diff hunk\n\n```diff\n{thread.diff_hunk}\n```")
    sections.append(f"## Conversation\n\n{history}")
    sections.append(
        "Decide whether to fix the code or reply only, edit files if you fix, "
        "and return your decision."
    )
    return "\n\n".join(sections)


def _render_resolved_thread(thread: ReviewThread) -> str:
    head = thread.comments[0]
    bot_replies = [c for c in thread.comments[1:] if c.author.endswith("[bot]")]
    summary = f"- `{thread.path}` — **{head.author}**: {head.body.strip()}"
    if bot_replies:
        last = bot_replies[-1]
        summary += f"\n  - **{last.author}** (resolved): {last.body.strip()}"
    return summary


def _has_staged_changes(repo_root: Path) -> bool:
    repo = Repo(str(repo_root))
    return repo.is_dirty(index=True, working_tree=False, untracked_files=False)


async def _process_thread(
    thread: ReviewThread,
    workspace: PRWorkspace,
    bot: CaiBot,
    prior_corrections: list[ReviewThread],
) -> ThreadResult:
    prompt = _format_thread_prompt(thread, workspace, prior_corrections)
    result = await _address_agent().run(
        prompt,
        deps=repo_deps(workspace.repo_root, write_dirs=[workspace.repo_root]),
        usage_limits=UsageLimits(request_limit=50),
    )
    decision: AddressDecision = result.output

    committed = False
    if decision.action == "fix":
        if not decision.commit_message:
            raise ValueError(
                f"agent returned action=fix without commit_message for thread {thread.id}"
            )
        stage_all(workspace.repo_root)
        if _has_staged_changes(workspace.repo_root):
            commit(
                workspace.repo_root,
                decision.commit_message,
                author_name="cai-bot",
                author_email="cai-bot@users.noreply.github.com",
            )
            committed = True

    reply_to_review_comment(
        bot, workspace.repo, workspace.number, thread.first_comment_id, decision.reply
    )

    resolved = False
    if decision.action == "fix" and committed:
        resolve_review_thread(bot, workspace.repo, thread.id)
        resolved = True

    return ThreadResult(
        thread_id=thread.id,
        path=thread.path,
        action=decision.action,
        committed=committed,
        resolved=resolved,
    )


@dataclass
class AddressState:
    bot: CaiBot
    workspace: PRWorkspace
    prior_corrections: list[ReviewThread] = field(default_factory=list)
    queue: list[ReviewThread] = field(default_factory=list)
    results: list[ThreadResult] = field(default_factory=list)
    any_committed: bool = False


class ListThreadsNode(BaseNode[AddressState, None, list[ThreadResult]]):
    """Fetch unresolved + resolved threads; populate the work queue."""

    async def run(
        self, ctx: GraphRunContext[AddressState]
    ) -> "ProcessThreadNode | PushNode":
        s = ctx.state
        s.queue = list(
            list_unresolved_threads(s.bot, s.workspace.repo, s.workspace.number)
        )
        s.prior_corrections = list(
            list_resolved_threads(s.bot, s.workspace.repo, s.workspace.number)
        )
        if not s.queue:
            return PushNode()
        return ProcessThreadNode()


class ProcessThreadNode(BaseNode[AddressState, None, list[ThreadResult]]):
    """Handle the next thread; loop while the queue still has work."""

    async def run(
        self, ctx: GraphRunContext[AddressState]
    ) -> "ProcessThreadNode | PushNode":
        s = ctx.state
        thread = s.queue.pop(0)
        result = await _process_thread(thread, s.workspace, s.bot, s.prior_corrections)
        s.results.append(result)
        s.any_committed = s.any_committed or result.committed
        if s.queue:
            return ProcessThreadNode()
        return PushNode()


class PushNode(BaseNode[AddressState, None, list[ThreadResult]]):
    """Push the PR branch once if any thread produced a commit."""

    async def run(
        self, ctx: GraphRunContext[AddressState]
    ) -> End[list[ThreadResult]]:
        s = ctx.state
        if s.any_committed:
            token = s.bot.token_for(s.workspace.repo)
            remote_url = (
                f"https://x-access-token:{token}@github.com/{s.workspace.repo}.git"
            )
            push_branch(
                s.workspace.repo_root,
                remote_url,
                s.workspace.head_branch,
                env={"GIT_TERMINAL_PROMPT": "0"},
            )
        return End(s.results)


address_graph: Graph[AddressState, None, list[ThreadResult]] = Graph(
    nodes=[ListThreadsNode, ProcessThreadNode, PushNode]
)


def address_pr(bot: CaiBot, workspace: PRWorkspace) -> list[ThreadResult]:
    """Run the per-thread loop synchronously, wrapped in a langfuse trace."""
    pr_ref = f"{workspace.repo}#{workspace.number}"
    state = AddressState(bot=bot, workspace=workspace)
    with langfuse_workflow(
        "cai-address",
        input={"pr": pr_ref, "branch": workspace.head_branch},
        metadata={"repo": workspace.repo, "pr_number": workspace.number},
    ):
        address_graph.run_sync(ListThreadsNode(), state=state)
    return state.results
