#!/usr/bin/env python3
"""Generate mermaid diagrams for every cai workflow into ``docs/workflows/``.

Run by the ``regen-workflow-graphs`` pre-commit hook so the docs always
reflect the live ``pydantic_graph.Graph`` topology in the source. Exits
non-zero if any docs file would change, which is what makes pre-commit
fail and re-stage the regenerated file in the same hook run.
"""
from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from cai.workflows.audit import audit_graph  # noqa: E402
from cai.workflows.fsm import solve_graph  # noqa: E402

DOCS_DIR = REPO_ROOT / "docs" / "workflows"


@dataclass
class WorkflowDoc:
    slug: str
    title: str
    nav_order: int
    blurb: str
    graph: object


WORKFLOWS: list[WorkflowDoc] = [
    WorkflowDoc(
        slug="solve",
        title="cai-solve",
        nav_order=1,
        blurb=(
            "Drives a GitHub issue or pull request through the same graph. "
            "Issues are explored, refined, implemented, and pushed as a new PR. "
            "PRs enter at the implement step with their unresolved review "
            "threads in the prompt, and the bundled fix is pushed in place."
        ),
        graph=solve_graph,
    ),
    WorkflowDoc(
        slug="audit",
        title="cai-audit",
        nav_order=2,
        blurb=(
            "Runs the audit agent against recent Langfuse traces and files "
            "proposed improvements as GitHub issues."
        ),
        graph=audit_graph,
    ),
]


def render(wf: WorkflowDoc) -> str:
    """Render the page body. The mermaid block is fenced so Just-the-Docs
    (with ``mermaid:`` enabled in ``_config.yml``) renders it as an SVG."""
    return (
        "---\n"
        f"title: {wf.title}\n"
        "parent: Workflows\n"
        f"nav_order: {wf.nav_order}\n"
        "---\n\n"
        f"# {wf.title}\n\n"
        f"{wf.blurb}\n\n"
        "## Graph\n\n"
        "<!-- AUTO-GENERATED by scripts/gen_workflow_graphs.py — do not edit. -->\n\n"
        "```mermaid\n"
        f"{wf.graph.mermaid_code()}\n"
        "```\n"
    )


def write_index() -> tuple[Path, str]:
    body = (
        "---\n"
        "title: Workflows\n"
        "nav_order: 5\n"
        "has_children: true\n"
        "---\n\n"
        "# Workflows\n\n"
        "Each cai-* CLI is implemented as a `pydantic_graph.Graph`. The "
        "diagrams on the child pages are regenerated from the live graph "
        "definitions by `scripts/gen_workflow_graphs.py` (wired as a "
        "pre-commit hook), so they always match the code.\n"
    )
    return DOCS_DIR / "index.md", body


def main() -> int:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    changed: list[Path] = []

    index_path, index_body = write_index()
    pages: list[tuple[Path, str]] = [(index_path, index_body)]
    pages.extend((DOCS_DIR / f"{wf.slug}.md", render(wf)) for wf in WORKFLOWS)

    for path, body in pages:
        existing = path.read_text() if path.exists() else None
        if existing != body:
            path.write_text(body)
            changed.append(path)

    if changed:
        for path in changed:
            print(f"updated {path.relative_to(REPO_ROOT)}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
