#!/usr/bin/env bash
# Regenerates CODEBASE_INDEX.md from the tracked file list.
# Descriptions are defined in the associative array below.
# Run from anywhere; the script always operates on the repo root.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
OUTPUT="$REPO_ROOT/CODEBASE_INDEX.md"

# ---------------------------------------------------------------------------
# Single source of truth for file descriptions.
# Add a new entry here whenever a file is added to the repo.
# ---------------------------------------------------------------------------
declare -A DESCRIPTIONS=(
  ["cai.py"]="Main CLI dispatcher — 16+ subcommands for the self-improvement loop"
  ["parse.py"]="Deterministic signal extractor from Claude Code JSONL transcripts"
  ["publish.py"]="GitHub issue publisher with fingerprint dedup"
  ["entrypoint.sh"]="Docker entrypoint — templates crontab, runs initial cycle, execs supercronic"
  ["install.sh"]="Interactive installer for end-users"
  ["Dockerfile"]="Container image definition (Python 3.12 + Node + claude-code CLI)"
  ["docker-compose.yml"]="Multi-service orchestration with named volumes"
  ["CLAUDE.md"]="Shared efficiency guidance loaded by all subagents"
  ["CODEBASE_INDEX.md"]="This file — static file-level index for fast agent orientation"
  ["README.md"]="Project documentation and usage guide"
  ["LICENSE"]="MIT license"
  [".env.example"]="Template for required environment variables"
  [".gitignore"]="Git ignore rules"
  [".claude/settings.json"]="Claude Code harness configuration"
  [".claude/agents/cai-analyze.md"]="Agent: parse transcript signals and raise auto-improve findings"
  [".claude/agents/cai-audit.md"]="Agent: audit issue queue and lifecycle state machine"
  [".claude/agents/cai-audit-triage.md"]="Agent: triage \`audit:raised\` findings with structured verdicts"
  [".claude/agents/cai-code-audit.md"]="Agent: read-only source tree audit for inconsistencies and dead code"
  [".claude/agents/cai-confirm.md"]="Agent: verify merged PRs actually resolved their issues"
  [".claude/agents/cai-cost-optimize.md"]="Agent: weekly cost-reduction analysis"
  [".claude/agents/cai-explore.md"]="Agent: autonomous exploration and benchmarking"
  [".claude/agents/cai-fix.md"]="Agent: smallest targeted code change for an auto-improve issue"
  [".claude/agents/cai-git.md"]="Agent: lightweight git operations subagent"
  [".claude/agents/cai-merge.md"]="Agent: assess PR correctness and emit merge verdict"
  [".claude/agents/cai-plan.md"]="Agent: generate detailed fix plan for an issue"
  [".claude/agents/cai-propose.md"]="Agent: weekly creative improvement proposals"
  [".claude/agents/cai-propose-review.md"]="Agent: review creative proposals for feasibility"
  [".claude/agents/cai-rebase.md"]="Agent: rebase-only conflict resolution"
  [".claude/agents/cai-refine.md"]="Agent: rewrite human-filed issues into structured plans"
  [".claude/agents/cai-review-docs.md"]="Agent: pre-merge documentation review"
  [".claude/agents/cai-review-pr.md"]="Agent: pre-merge ripple-effect review"
  [".claude/agents/cai-revise.md"]="Agent: handle review comments on auto-improve PRs"
  [".claude/agents/cai-select.md"]="Agent: evaluate and select best fix plan"
  [".claude/agents/cai-spike.md"]="Agent: research spike for needs-spike issues"
  [".claude/agents/cai-update-check.md"]="Agent: check for new Claude Code releases"
  [".github/workflows/admin-only-label.yml"]="CI: restrict auto-improve:requested label to admins"
  [".github/workflows/cleanup-pr-context.yml"]="CI: clean up PR context on close"
  [".github/workflows/docker-publish.yml"]="CI: build and publish Docker image to Docker Hub"
  [".github/workflows/check-index.yml"]="CI: verify CODEBASE_INDEX.md is up to date"
  ["docs/_config.yml"]="Jekyll configuration for GitHub Pages docs"
  ["docs/index.md"]="Documentation site landing page"
  ["scripts/generate-index.sh"]="Generator script for CODEBASE_INDEX.md"
  ["tests/__init__.py"]="Test package init"
  ["tests/test_multistep.py"]="Tests for multi-step plan support"
  ["tests/test_parse.py"]="Tests for parse.py signal extraction"
  ["tests/test_publish.py"]="Tests for publish.py issue publishing"
  ["tests/test_rollback.py"]="Tests for rollback functionality"
)

# ---------------------------------------------------------------------------
# Generate the markdown table
# ---------------------------------------------------------------------------
{
  cat <<'HEADER'
# Codebase Index

> Auto-generated by `scripts/generate-index.sh`. Do not edit manually —
> update the descriptions in the generator script instead.

| File | Purpose |
|------|---------|
HEADER

  git -C "$REPO_ROOT" ls-files | sort | while IFS= read -r f; do
    desc="${DESCRIPTIONS[$f]:-TODO: add description}"
    printf '| `%s` | %s |\n' "$f" "$desc"
  done
} > "$OUTPUT"

echo "Written: $OUTPUT"
