#!/usr/bin/env python3
"""Regenerate docs/fsm.md from cai_lib.fsm.

Renders ISSUE_TRANSITIONS and PR_TRANSITIONS as Mermaid stateDiagram-v2
blocks so GitHub Pages (just-the-docs + mermaid) can display the
current auto-improve lifecycle graph.

Run from anywhere; the script always writes to <repo>/docs/fsm.md.
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from cai_lib.fsm import (  # noqa: E402
    ISSUE_TRANSITIONS, PR_TRANSITIONS, render_fsm_mermaid,
)

OUTPUT = REPO_ROOT / "docs" / "fsm.md"

PAGE = """---
title: Lifecycle FSM
nav_order: 5
---

# Auto-improve lifecycle FSM

> Auto-generated by `scripts/generate-fsm-docs.py` from
> `cai_lib/fsm.py`. Do not edit this file by hand — edit the FSM
> definition and the CI workflow will regenerate it.

## Issue state machine

```mermaid
{issue_diagram}
```

## PR state machine

```mermaid
{pr_diagram}
```
"""


def main() -> int:
    issue_diagram = render_fsm_mermaid(ISSUE_TRANSITIONS)
    pr_diagram = render_fsm_mermaid(PR_TRANSITIONS)
    OUTPUT.write_text(PAGE.format(
        issue_diagram=issue_diagram,
        pr_diagram=pr_diagram,
    ))
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
