#!/usr/bin/env python3
"""Regenerate docs/fsm.md from cai_lib.fsm (and its submodules).

Renders ISSUE_TRANSITIONS and PR_TRANSITIONS as Mermaid stateDiagram-v2
blocks so GitHub Pages (just-the-docs + mermaid) can display the
current auto-improve lifecycle graph. Imports from cai_lib.fsm which
re-exports from fsm_states, fsm_transitions, and fsm_confidence.

Run from anywhere; the script always writes to <repo>/docs/fsm.md.
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from transitions import Machine  # noqa: E402

from cai_lib.fsm import (  # noqa: E402
    ISSUE_TRANSITIONS, PR_TRANSITIONS, render_fsm_mermaid,
)
from cai_lib.fsm_states import IssueState, PRState  # noqa: E402

OUTPUT = REPO_ROOT / "docs" / "fsm.md"


def _validate_catalog(state_enum, transition_list, name: str) -> None:
    """Build a :class:`transitions.Machine` from the catalog; raise on drift.

    Surfaces unknown state references as ``ValueError`` at CI time so
    catalog typos can never sneak into the Mermaid output. ``name`` is
    the catalog identifier used for error context if the call raises.
    """
    states = [s.name for s in state_enum]
    transitions_spec = [
        {
            "trigger": t.name,
            "source": t.from_state.name,
            "dest": t.to_state.name,
        }
        for t in transition_list
    ]
    Machine(
        model=None,
        states=states,
        transitions=transitions_spec,
        initial=states[0],
        auto_transitions=False,
        ignore_invalid_triggers=True,
    )

PAGE = """---
title: Lifecycle FSM
nav_order: 5
---

# Auto-improve lifecycle FSM

> Auto-generated by `scripts/generate-fsm-docs.py` from
> `cai_lib/fsm.py` (re-export of fsm_states, fsm_transitions, fsm_confidence).
> Do not edit this file by hand — edit the FSM definition and the CI
> workflow will regenerate it.

## Issue state machine

```mermaid
{issue_diagram}
```

## PR state machine

```mermaid
{pr_diagram}
```
"""


def main() -> int:
    _validate_catalog(IssueState, ISSUE_TRANSITIONS, "ISSUE_TRANSITIONS")
    _validate_catalog(PRState, PR_TRANSITIONS, "PR_TRANSITIONS")
    issue_diagram = render_fsm_mermaid(ISSUE_TRANSITIONS)
    pr_diagram = render_fsm_mermaid(PR_TRANSITIONS)
    OUTPUT.write_text(PAGE.format(
        issue_diagram=issue_diagram,
        pr_diagram=pr_diagram,
    ))
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
